# Generated by Django 3.1.6 on 2021-05-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airsoftgun',
            name='type_list',
            field=models.CharField(choices=[('Автомат', 'Автомат'), ('Пистолет', 'Пистолет'), ('Винтовка', 'Винтовка'), ('Гранатомет', 'Гранатомет'), ('Дробовик', 'Дробовик'), ('Пулемет', 'Пулемет'), ('Нож', 'Нож')], default=123, max_length=50),
            preserve_default=False,
        ),
    ]
