# Generated by Django 3.1.6 on 2021-05-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210522_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=120)),
                ('key', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='airsoftgun',
            name='Image',
            field=models.ImageField(upload_to='airsoftgun/'),
        ),
        migrations.AlterField(
            model_name='airsoftgun',
            name='Status',
            field=models.CharField(choices=[('В наличии', 'В наличии'), ('Нет в наличии', 'Нет в наличии')], max_length=50),
        ),
        migrations.AlterField(
            model_name='airsoftgun',
            name='Vendor',
            field=models.CharField(choices=[('Неизвестно', 'Неизвестно'), ('Cyma', 'Cyma'), ('G&G', 'G&G'), ('Tokyo Marui', 'Tokyo Marui'), ('WE', 'WE'), ('KJW', 'KJW'), ('KWA', 'KWA'), ('KWC', 'KWC'), ('T&D', 'T&D')], max_length=50),
        ),
    ]
