# Generated by Django 3.1.6 on 2021-05-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210529_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airsoftgun',
            name='Status',
        ),
        migrations.AddField(
            model_name='airsoftgun',
            name='Value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
