# Generated by Django 3.1.6 on 2021-06-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210531_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='airsoftgun',
            name='Battery',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airsoftgun',
            name='Equipment',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airsoftgun',
            name='Girbox',
            field=models.CharField(choices=[('V1', 'Ver. 1'), ('V2', 'Ver. 2'), ('V3', 'Ver. 3'), ('V4', 'Ver. 4'), ('V5', 'Ver. 5'), ('V6', 'Ver. 6'), ('V7', 'Ver. 7'), ('V8', 'Ver. 8'), ('V9', 'Ver. 9'), ('V2.5', 'Ver. 2,5'), ('M249/PKM', 'M249/PKM'), ('M60', 'M60')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airsoftgun',
            name='Length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airsoftgun',
            name='Speed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airsoftgun',
            name='Weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
