# Generated by Django 3.1.6 on 2021-06-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_airsoftgun_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airsoftgun',
            name='Girbox',
            field=models.CharField(choices=[('отсутствует', 'отсутствует'), ('V1', 'Ver. 1'), ('V2', 'Ver. 2'), ('V3', 'Ver. 3'), ('V4', 'Ver. 4'), ('V5', 'Ver. 5'), ('V6', 'Ver. 6'), ('V7', 'Ver. 7'), ('V8', 'Ver. 8'), ('V9', 'Ver. 9'), ('V2.5', 'Ver. 2,5'), ('M249/PKM', 'M249/PKM'), ('M60', 'M60')], max_length=50),
        ),
    ]
