# Generated by Django 3.1.6 on 2021-06-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20210603_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='About',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='BallWeight_list',
            field=models.CharField(choices=[('нет', 'нет'), ('0.20', '0.20'), ('0.25', '0.25'), ('0.28', '0.28')], max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='Vendor',
            field=models.CharField(choices=[('Неизвестно', 'Неизвестно'), ('G&G', 'G&G'), ('AimTop', 'AimTop'), ('FL-Airsoft', 'FL-Airsoft')], max_length=50),
        ),
    ]
