# Generated by Django 3.1.6 on 2021-06-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20210603_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='BallWeight_list',
            new_name='BallWeight',
        ),
    ]
