# Generated by Django 3.1.6 on 2021-06-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20210603_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='Gas',
            field=models.CharField(choices=[('нет', 'нет'), ('GreenGas', 'Green Gas'), ('CO2', 'CO2')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
