# Generated by Django 3.1.6 on 2021-06-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_material_gas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Gas',
            field=models.CharField(choices=[('нет', 'нет'), ('Green Gas', 'Green Gas'), ('CO2', 'CO2')], max_length=50),
        ),
    ]
