# Generated by Django 3.1.6 on 2021-06-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20210603_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='material/')),
                ('Vendor', models.CharField(choices=[('Неизвестно', 'Неизвестно'), ('FMA', 'FMA'), ('Stich Profi', 'Stich Profi'), ('ASR', 'ASR')], max_length=50)),
                ('Type_list', models.CharField(choices=[('Разгрузочная система', 'Разгрузочная система'), ('Подсумок', 'Подсумок')], max_length=50)),
                ('Color', models.CharField(choices=[('нет', 'нет'), ('Multicam', 'Multicam'), ('A-TACS', 'A-TACS'), ('МОХ', 'МОХ'), ('EMR', 'EMR'), ('Marpat', 'Marpat'), ('Coyote Brown', 'Coyote Brown'), ('Черный', 'Черный'), ('Олива', 'Олива'), ('Разноцветный', 'Разноцветный')], max_length=50)),
                ('Pouch', models.CharField(choices=[('нет', 'нет'), ('Административный', 'Административный'), ('Гранатный', 'Гранатный'), ('Магазинный для АК/M4/M16', 'Магазинный для АК/M4/M16'), ('Медицинский', 'Медицинский'), ('Под бутылку', 'Под бутылку'), ('Под сброс магазинов', 'Под сброс магазинов'), ('Утилитарный', 'Утилитарный'), ('Прочие подсумки', 'Прочие подсумки')], max_length=50)),
                ('Holster', models.CharField(choices=[('нет', 'нет'), ('Beretta', 'Beretta'), ('Colt', 'Colt'), ('Glock', 'Glock'), ('Hi-Capa', 'Hi-Capa'), ('ПЯ Грач', 'ПЯ Грач'), ('Универсальная', 'Универсальная')], max_length=50)),
                ('Material', models.CharField(max_length=120)),
                ('About', models.TextField()),
                ('Value', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
