# Generated by Django 3.1.6 on 2021-06-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='material/')),
                ('Vendor', models.CharField(choices=[('Неизвестно', 'Неизвестно'), ('FMA', 'FMA'), ('Stich Profi', 'Stich Profi'), ('ASR', 'ASR')], max_length=50)),
                ('Type_list', models.CharField(choices=[('Шлем', 'Шлем'), ('Маска', 'Маска'), ('Очки', 'Очки'), ('Перчатки', 'Перчатки')], max_length=50)),
                ('Color', models.CharField(choices=[('нет', 'нет'), ('Multicam', 'Multicam'), ('A-TACS', 'A-TACS'), ('МОХ', 'МОХ'), ('EMR', 'EMR'), ('Marpat', 'Marpat'), ('Coyote Brown', 'Coyote Brown'), ('Черный', 'Черный'), ('Олива', 'Олива'), ('Разноцветный', 'Разноцветный')], max_length=50)),
                ('Weight', models.TextField()),
                ('Glasses_type', models.CharField(choices=[('нет', 'нет'), ('Открытые', 'Открытые'), ('Закрытые', 'Закрытые')], max_length=50)),
                ('Material', models.CharField(max_length=120)),
                ('About', models.TextField()),
                ('Value', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
