# Generated by Django 3.1.6 on 2021-06-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_protection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protection',
            name='Weight',
            field=models.IntegerField(),
        ),
    ]
