# Generated by Django 3.1.6 on 2021-06-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_additional'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=120)),
                ('Phone', models.CharField(max_length=120)),
                ('Email', models.CharField(max_length=120)),
                ('Address', models.TextField()),
                ('Comment', models.TextField()),
                ('Order', models.TextField()),
                ('Price', models.IntegerField()),
                ('Status', models.CharField(choices=[('Обработывается', 'Обработывается'), ('Доставляется', 'Доставляется'), ('Готово к выдаче', 'Готово к выдаче'), ('Выдано', 'Выдано')], max_length=50)),
            ],
        ),
    ]
